project:
  type: website

website:
  title: "Aphiaut's Blog"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/etc5523-2022/blog-aphiaut
format:
  html:
    theme: lumen
    css: styles.css



