project:
  type: website

website:
  title: "Aphiaut's Website"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/aphiaut
format:
  html:
    theme: lumen
    css: styles.css



